// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "Web API Key", // You'll get this below
    appId: "1:515189087401:android:adbfb49970f875cf51db8",
    messagingSenderId: "515189087401",
    projectId: "mindhaven-e1ed1",
    storageBucket: "mindhaven-e1ed1.appspot.com",
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "DUMMY_FOR_NOW",
    appId: "DUMMY_FOR_NOW",
    messagingSenderId: "DUMMY_FOR_NOW",
    projectId: "mindhaven-e1ed1",
    storageBucket: "mindhaven-e1ed1.appspot.com",
  );
}
